<a href="https://colab.research.google.com/github/manojpawar94/machine-learning-in-python/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

### **Import Numpy**

In [1]:
# import numpy library
import numpy as np

### **Check version of Numpy** 

In [2]:
# check the version of the numpy library
print(np.__version__)

1.18.5


### **Create array using Numpy**

**NumPy** is used to work with arrays. The array object in NumPy is called **ndarray**. We can create a **NumPy** ndarray object by using the array() function.

In [3]:
# create numpy arrray 
my_array = np.array([1,2,3,4,5])

# print numpy array 
print(my_array)

# type of the array
print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### **Create array of differnt dimensions using the Numpy**

In [4]:
# create zero dimension array or scalar
scalar_arr = np.array(42)

print(scalar_arr)

42


In [5]:
# create one dimensional array
one_d_arr1 = np.array([1,2,3,4,5])

one_d_arr2 = np.array((1,2,3,4,5))

print('one dimensional array using list: ', one_d_arr1)
print('one dimensional array using tuple: ', one_d_arr2)

one dimensional array using list:  [1 2 3 4 5]
one dimensional array using tuple:  [1 2 3 4 5]


In [10]:
# create two dimensional array 
two_d_arr1 = np.array([[1,2,3],[4,5,6]])

two_d_arr2 = np.array(([1,2,3],[4,5,6]))

two_d_arr3 = np.array(((1,2,3),(4,5,6)))

two_d_arr4 = np.array([(1,2,3),(4,5,6)])

print('two dimensional array using list of lists:\n',two_d_arr1)
print('two dimensional array using tuple of lists:\n',two_d_arr2)
print('two dimensional array using tuple of tuples:\n',two_d_arr3)
print('two dimensional array using list of tuples:\n',two_d_arr4)

two dimensional array using list of lists:
 [[1 2 3]
 [4 5 6]]
two dimensional array using tuple of lists:
 [[1 2 3]
 [4 5 6]]
two dimensional array using tuple of tuples:
 [[1 2 3]
 [4 5 6]]
two dimensional array using list of tuples:
 [[1 2 3]
 [4 5 6]]


In [11]:
# create three dimensional array
three_d_arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(three_d_arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### **Check the dimension of Numpy dnarray object**
NumPy Arrays provides the **ndim** attribute that returns an integer that tells us how many dimensions the array have.

In [12]:
# checking the dimension of the array
print('The dimension of one_d_arr1 is', one_d_arr1.ndim)
print('The dimension of two_d_arr1 is', two_d_arr1.ndim)
print('The dimension of three_d_arr is', three_d_arr.ndim)

The dimension of one_d_arr1 is 1
The dimension of two_d_arr1 is 2
The dimension of three_d_arr is 3


### **Higher demension array**